### ISSUE TITLE
failure to estimate "casal2 stopped working"

### ISSUE THREAD

**Issue by smormede** [NIWAFisheriesModelling/CASAL2#210]
This model is the sexed Ross Sea region full model to 2015. The unsexed equivalent runs fine. 

This model runs fine on -r (and -i -r), but when doing an estimation (-e) casal2 exits with new window "casal2.exe has stopped working". Prior to that it prints the first about to evaluate function and the first about to evaluate gradient with the starting parameters. I had three adol tape files (in, op and rl, not in the zip file).

It also fails when starting from the casal estimated values (-i MPDcasal.dat -e).

Thanks

Sophie
[CASAL2 sexed RSR model.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1580362/CASAL2.sexed.RSR.model.zip)

**Comment by smormede** [comment]
Possibly a memory issue: I just tested with only 10 years of tagging data (instead of 14) and that's working ok. 
single sex: 15 categories is ok, took about 14 minutes
two-sex 5 years of tagging: 12 categories is ok
two-sex 10 years of tagging: 22 categories is ok but took 44 minutes
two-sex 14 years of tagging: 30 categories falls over.

File for the 10 years of tagging attached.
[CASAL2 sexed 10 years tagging RSR.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1580571/CASAL2.sexed.10.years.tagging.RSR.zip)

**Comment by Zaita** [comment]
Note. This is a bug. There is a memory corruption occurring that is causing the crash.

**Comment by Zaita** [comment]
https://github.com/NIWAFisheriesModelling/CASAL2/commit/5916b9ee912777a5b11b0ef40189482fc74164f3

This commit introduces a bug where it was reading the value from a vector that didn't exist. I've fixed and committed this. The models attached to this issue now work.

@smormede Please confirm and close issue

**Comment by Craig44** [comment]
Can this issue be closed @smormede ?

**Comment by smormede** [comment]
Hi there,

Still crashing for me, using casal2 version 2018-02-08 05:35:27 UTC (rev. d1e7bda)

example attached.

@Zaita 
@Craig44 
[CASAL2.crash.largepartitions.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1717907/CASAL2.crash.largepartitions.zip)

**Comment by Zaita** [comment]
[crash_large_partition.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/2454681/crash_large_partition.zip)

Tested with latest build. Had to modify config file for new syntax but this works as expected. No crash, estimate took 36mins.

**Comment by smormede** [comment]
tested and it looks fine now. thanks
